# Generated by Django 5.1.4 on 2025-01-05 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('OTHER', 'Other'), ('CPU', 'CPU'), ('GPU', 'GPU'), ('RAM', 'RAM'), ('MB', 'Motherboard')], default='OTHER', max_length=100),
        ),
        migrations.AddField(
            model_name='item',
            name='label',
            field=models.CharField(choices=[('PR', 'primary'), ('SC', 'secondary'), ('DR', 'danger')], default='PR', max_length=2),
        ),
    ]
